### ISSUE TITLE
ModuleNotFoundError: No module named 'hparams'

### ISSUE THREAD

**Issue by aliyasineser** [naotokui/SpecGAN#1]
Cannot import module. In hparams.py there was no class. Didn't change any of the code.
Full error:

Traceback (most recent call last):
  File "preprocess_audio.py", line 31, in <module>
    from utils import audio_tools as audio
  File "Path\SpecGAN\utils\audio_tools.py", line 11, in <module>
    from hparams import hparams
ModuleNotFoundError: No module named 'hparams'

**Comment by aliyasineser** [comment]
I copied the hparams variable and didn't use hparams.py for now. Looks like works.
